# Generated by Django 5.1 on 2025-05-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="contact_info",
            new_name="phone",
        ),
    ]
